


******************
FUNCTION FORMAT_DBF

CREATE TABLE SB_IMPRT ;
    ( VOTERID     C(  9), ;
      FIRST       C( 30), ;
      LAST        C( 40), ;
      MIDDLE      C( 30), ;
      SUFFIX      C(  5), ;
      PARTYCOD    C(  3), ;
      VOTING_D    C( 10), ;
      ADD1        C(100), ;
      ADD2        C(100), ;
      ADD3        C(100), ;
      CITY        C(100), ;
      MUNICIPALI  C( 30), ;
      STATE       C(  2), ;
      ZIP         C(  5), ;
      ZIP4        C(  4), ;
      MAIL_ADD1   C(100), ;
      MAIL_ADD2   C(100), ;
      MAIL_ADD3   C(100), ;
      MAIL_CITY   C(100), ;
      MAIL_STATE  C( 20), ;
      MAIL_ZIP    C(  5), ;
      MAIL_ZIP4   C(  4), ;
      MAIL_COUN   C(  4), ;
      PARTY       C( 10), ;
      VOTER_STAT  C(  2), ;
      MWD         C( 40), ;
      WARD        C(  2), ;
      DISTRICT    C(  2), ;
      MUNICI_COD  C(  4), ;
      ELEC_NAME   C( 40), ;
      ELEC_TYPE   C( 50), ;
      ELEC_DATE   C( 10), ;
      POLL_OPEN   C(  8), ;
      POLL_CLOSE  C(  8), ;
      POLL_LOCAT  C(100), ;
      POLL_PLACE  C(100), ;
      POLL_STREE  C(195), ;
      POLL_CITY   C(195), ;
      POLL_MUNIC  C( 30), ;
      POLL_STATE  C(  2), ;
      POLL_ZIP    C( 10), ;
      POLL_AREA   C(100), ;
      POLL_ACCE   C( 20), ;
      ADA_STREE   C( 10), ;
      ADA_NAME    C( 40), ;
      ADA_ADD2    C( 30), ;
      ADA_ADD3    C( 30), ;
      ADA_MUNICI  C( 30), ;
      ADA_STATE   C(  2), ;
      ADA_ZIP4    C( 10), ;
      BARCODE     C(  9), ;
      OLD_ADD1    C( 40), ;
      OLD_ADD2    C( 40), ;
      OLD_ADD3    C( 40), ;
      OLD_CITY    C( 40), ;
      OLD_STATE   C(  2), ;
      OLD_ZIP     C(  5), ;
      STATUS      C(  5);
     )


